name: Deploy to EC2

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/server

            # Force Git to use SSH remote to avoid HTTPS credential prompts
            git remote set-url origin git@github.com:TeamIndigo4/sequelizer-generator.git

            echo "Current Git Remote URL:"
            git remote -v

            # Pull latest code
            git pull origin main

            cd server

            # Restart backend
            pm2 restart backend || pm2 start app.js --name backend

