name: Deploy to EC2

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/server

            # Ensure Git is using SSH instead of HTTPS (idempotent)
            git remote set-url origin git@github.com:TeamIndigo4/sequelizer-generator.git

            # Pull latest changes from GitHub (no credentials needed now)
            git pull origin main

            cd server

            # Restart backend service using PM2
            pm2 restart backend || pm2 start app.js --name backend
