name: Deploy to EC2

on:
  push:
    paths:
      - 'server/**'
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/server
            git pull origin deployment

            cd server 

            echo "${{ secrets.ENV_FILE }}" > .env

            pm2 restart backend || pm2 start app.js --name backend
